server:
  port: 8080
dubbo:
  application:
    name: dubbo-provider
    qosEnable: true
    qosAcceptForeignIp: true
  registry:
    address: zookeeper://47.106.238.98:2181
  protocol:
    name: dubbo
    port: 28880
  service:
    version: 1.0.0
    name: dobbo-service
